---

  - name: Influx Server
    hosts: influxdb
    remote_user: ec2-user
    become: yes

    roles:
      - influxdb

  - name: nginx Server
    hosts: nginx
    remote_user: ec2-user
    become: yes

    roles:
      - nginx

