---
# tasks file for influxdb
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: influxdb.repo 
    dest: /etc/yum.repos.d/influxdb.repo

- name: Install the latest version of influx
  ansible.builtin.yum:
    name: influxdb
    state: latest

- name: Start service influx, if not started
  ansible.builtin.service:
    name: influxdb 
    state: started
    enabled: yes
